# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In - App Devmenu if RN >= 0.43
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'ICGVideoTrimmer', :git => 'https://github.com/nixplay/ICGVideoTrimmer.git'
  pod 'SDAVAssetExportSession', :git => 'https://github.com/nixplay/SDAVAssetExportSession.git'
  # Pods for example
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-video-trimmer', :path => '../node_modules/react-native-video-trimmer/ios'
  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

end
